spring.application.name=quiz-app
spring.data.mongodb.uri=mongodb://localhost:27017/quizdb

jwt.secret=ChangeThisSecretKeyToSomethingLongAndRandomInProduction123456
jwt.expiration-ms=86400000

server.port=8080

spring.main.allow-bean-definition-overriding=true

spring.main.allow-circular-references=true